language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer selfupdate

install:
  - composer install --prefer-source --dev

script:
  - php bin/phpunit --coverage-clover build/logs/clover.xml
  - php bin/phpcs -n --standard=PSR1,PSR2 --report=full src/
##  - php bin/phpmd src/ text build/rulesets/phpmd.xml

after_script:
  - php vendor/bin/coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'

matrix:
    fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/75311bf6cc64a613a399
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
