language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer selfupdate
  - composer install --prefer-source --dev

install:
    - |
        sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then \
          git clone git://github.com/bitcoin/secp256k1.git libsecp256k1 \
          && cd libsecp256k1 \
          && ./autogen.sh && ./configure && make && sudo make install \
          && cd ..; fi'
    - |
        sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then \
          git clone git://github.com/Bit-Wasp/secp256k1-php
          && cd secp256k1-php/secp256k1 \
          && phpize && ./configure && make && sudo make install \
          && cd ../..; fi'
    - composer update

script:
  - php bin/phpunit --coverage-clover build/logs/clover.xml
  - php bin/phpcs -n --standard=PSR1,PSR2 --report=full src/
##  - php bin/phpmd src/ text build/rulesets/phpmd.xml

after_script:
  - php vendor/bin/coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'

matrix:
    fast_finish: true
