language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer selfupdate
  - composer install --prefer-source --dev

install:
  - composer install

script:
  - php bin/phpunit -c build/ --coverage-clover build/logs/clover.xml
  - php bin/phpcs -n --standard=PSR1,PSR2 --report=full src/
##  - php bin/phpmd src/ text build/rulesets/phpmd.xml

after_script:
  - ls -alh build/logs

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
